driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
platforms:
  - name: ubuntu-18.04
    driver_config:
      box: nrel/CentOS-6.5-x86_64
      box_url: https://app.vagrantup.com/nrel/boxes/CentOS-6.5-x86_64
suites:
  - name: default
run_list:
  - recipe[bootstrap]

