Parameters:
  KeyPair:
    Type: "AWS::EC2::KeyPair::KeyName"

Resources:
  JenkinsSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupName: "JenkinsSG"
      GroupDescription: "Allows all ingress on 80 and 443"
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
        - IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          FromPort: 443
          ToPort: 443
        - IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
  JenkinsInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0ac019f4fcb7cb7e6"
      SecurityGroups:
        - !Ref "JenkinsSG"
      KeyName: !Ref "KeyPair"
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - "apt update && apt upgrade -y"
              - "apt install git -y"
              - "sudo -H -u ubuntu -c 'git clone git@github.com:danielc2013/jenkins-quick-deploy'"
